apiVersion: apps/v1
kind: Deployment
metadata:
  name: mideployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
      - name: mideployment-container
        image: iesgn/test_web:latest
        ports:
        - containerPort: 80