apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  # Estrategia de actualización: RollingUpdate
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: mi-contenedor
        image: nginx
        ports:
        - containerPort: 80
      restartPolicy: Always